### ISSUE TITLE
dirs file may be obsolete

### ISSUE THREAD

**Issue by szepeviktor** [Avature/dh-make-php#7]
Could we drop
https://github.com/Avature/dh-make-php/blob/master/pecl.template/dirs
and the associated `sed`-s?

**Comment by jvrsantacruz** [comment]
I'd rather keep it, as posinst scripts assume this directory is in place.  
This is probably already created by a previous dependency, but I think is better to be explicit about needing it.

**Comment by szepeviktor** [comment]
From PHP 7 on `usr/lib/php5` becomes `usr/lib/php/7.0`
